default: &default
  endpoint: 'https://acme-v01.api.letsencrypt.org/'
  email: 'samlau95@gmail.com'
  domain: "instructor.rootsofsuccess.org"

  # in Rails.root, path to private key
  # private_key: 'key/keyfile.pem'

  # Private key stored in the database
  # private_key_in_db: true

  # in Rails.root, path where certificates will be stored
  # NOTE: on Heroku, this variable is ignored
  # output_cert_dir: 'certificates'

  # in Rails.root, path where challenge token will be stored
  # in situations when database will not be used
  # NOTE: on Heroku, comment out this line and use the database
  # challenge_dir_name: 'challenge'

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
